### PR TITLE
Preserve paragraphs marks using a WEBVTT comment

### PR DESCRIPTION
**Pull request by bradmsmith**
Per pculture/unisubs/issues/2295

### CODE REVIEW

**Comment by bendk** [comment]
This change looks great and I hope to pull it in soon.  The one thing that I think we need is for you to fill out a contributor form assigning the copyright to PCF.  If that sounds alright to you, we should be sending the form shortly.

**Comment by bradmsmith** [comment]
Great

**Comment by bendk** [comment]
Can you send me an email at ben@pculture.org?  I'll respond with the agreement.

**Comment by bendk** [comment]
Thanks for the contribution!  This will be active the next time we deploy (I'll try to do that next week).

**Pull request merged**
